const regions = {
    countries: {
      canada: "Canada",
      usa: "USA"
    },
    provinces: {
      ab: "Alberta",
      bc: "British Columbia",
      mb: "Manitoba",
      nb: "New Brunswick",
      nf: "Newfoundland and Labrador",
      ns: "Nova Scotia",
      nu: "Nunavut",
      nt: "Northwest Territories",
      on: "Ontario",
      pe: "Prince Edward Island",
      qc: "Quebec",
      sk: "Saskatchewan",
      yt: "Yukon"
    },
    unitedstates: {
      al: "Alabama",
      ak: "Alaska",
      az: "Arizona",
      ar: "Arkansas",
      ca: "California",
      co: "Colorado",
      ct: "Connecticut",
      dc: "District of Columbia",
      de: "Delaware",
      fl: "Florida",
      ga: "Georgia",
      hi: "Hawaii",
      id: "Idaho",
      il: "Illinois",
      in: "Indiana",
      ia: "Iowa",
      ks: "Kansas",
      ky: "Kentucky",
      la: "Louisiana",
      me: "Maine",
      md: "Maryland",
      ma: "Massachusetts",
      mi: "Michigan",
      mn: "Minnesota",
      ms: "Mississippi",
      mo: "Missouri",
      mt: "Montana",
      ne: "Nebraska",
      nv: "Nevada",
      nh: "New Hampshire",
      nj: "New Jersey",
      nm: "New Mexico",
      ny: "New York",
      nc: "North Carolina",
      nd: "North Dakota",
      oh: "Ohio",
      ok: "Oklahoma",
      or: "Oregon",
      pa: "Pennsylvania",
      ri: "Rhode Island",
      sc: "South Carolina",
      sd: "South Dakota",
      tn: "Tennessee",
      tx: "Texas",
      ut: "Utah",
      vt: "Vermont",
      va: "Virginia",
      wa: "Washington",
      wv: "West Virginia",
      wi: "Wisconsin",
      wy: "Wyoming",
      as: "American Samoa",
      gu: "Guam",
      mp: "Northern Mariana Islands",
      pr: "Puerto Rico",
      um: "United States Minor Outlying Islands",
      vi: "Virgin Islands"
    }
};

export default regions;